@startuml
title 基于GitHub的实验管理平台--用例图
actor teachers
actor students
actor users
students --|>users 
teachers --|>users 

package 业务用例集 {
teachers --up-> (评定成绩)
teachers --up-> (学生列表)
students --up-> (学生列表)
students --up-> (查看成绩)
}

package 用户用例集 {
users ---> (登录)
users ---> (登出)
users ---> (查看用户信息)
users ---> (修改用户信息)
users ---> (修改密码)
}
@enduml
